<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\frameworks\archon-framework\Archon\Archon.Application\Archon.Application.csproj" />
    <ProjectReference Include="..\IntegrationPlataform.Domain\IntegrationPlataform.Domain.csproj" />
  </ItemGroup>

</Project>
