<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.5" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.13.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\frameworks\archon-framework\Archon\Archon.Api\Archon.Api.csproj" />
    <ProjectReference Include="..\..\..\..\frameworks\archon-framework\Archon\Archon.Infrastructure\Archon.Infrastructure.csproj" />
    <ProjectReference Include="..\IntegrationPlataform.Application\IntegrationPlataform.Application.csproj" />
    <ProjectReference Include="..\IntegrationPlataform.Infrastructure\IntegrationPlataform.Infrastructure.csproj" />
  </ItemGroup>

</Project>
